In [1]:
import numpy as np
import random #`import numpy as np, random` imports the `numpy` library as `np` and the `random` module in one line.

In [3]:
np.random.random(1) #`np.random.random(1)` generates a random float between 0 and 1 in a 1-element array.

array([0.18215863])

In [5]:
np.random.random((3,3)) #`np.random.random((3, 3))` generates a 3x3 array with random float values between 0 and 1.

array([[0.13933613, 0.57963522, 0.99626271],
       [0.54919723, 0.00443036, 0.0670632 ],
       [0.9445252 , 0.41386674, 0.73732376]])

In [9]:
np.random.randint(1,4) #`np.random.randint(1, 4)` generates a random integer between 1 (inclusive) and 4 (exclusive).

1

In [13]:
np.random.randint(1,4,(4,4)) #`np.random.randint(1, 4, (4, 4))` generates a 4x4 array with random integers between 1 (inclusive) and 4 (exclusive).

array([[1, 3, 3, 1],
       [1, 1, 2, 1],
       [1, 1, 3, 3],
       [1, 1, 2, 3]])

In [15]:
np.random.randint(1,4,(2,4,4)) #`np.random.randint(1, 4, (2, 4, 4))` generates a 3D array with shape (2, 4, 4) containing random integers between 1 (inclusive) and 4 (exclusive).

array([[[3, 1, 2, 2],
        [3, 1, 3, 2],
        [1, 2, 1, 2],
        [3, 3, 3, 3]],

       [[2, 2, 2, 3],
        [1, 3, 2, 3],
        [1, 3, 2, 2],
        [2, 1, 1, 1]]])

In [19]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))#`np.random.seed(10)` sets the random seed to 10 for reproducibility, and `np.random.randint(1, 4, (2, 4, 4))` generates a 3D array with shape (2, 4, 4) containing random integers between 1 (inclusive) and 4 (exclusive), based on the fixed seed.

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [21]:
2**32-1

4294967295

In [23]:
np.random.rand(3)#`np.random.rand(3)` generates a 1D array of 3 random float values between 0 and 1.

array([0.13145815, 0.41366737, 0.77872881])

In [25]:
np.random.rand(3,3)#`np.random.rand(3, 3)` generates a 3x3 array of random float values between 0 and 1.

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [27]:
np.random.randn(3,3) #`np.random.randn(3, 3)` generates a 3x3 array of random values from a standard normal distribution (mean = 0, standard deviation = 1).

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

In [29]:
x=[1,2,3,4]
np.random.choice(x) #`np.random.choice(x)` randomly selects one element from the list `x`.

1

In [31]:
for i in range(20):
    print(np.random.choice(x)) #`for i in range(20): print(np.random.choice(x))` randomly selects and prints one element from the list `x` 20 times.

1
1
2
1
4
1
1
3
1
3
3
1
4
2
1
4
2
3
3
2


In [33]:
x

[1, 2, 3, 4]

In [35]:
np.random.permutation(x) #`np.random.permutation(x)` randomly shuffles the elements of the array `x` and returns a new array with the shuffled order.

array([1, 2, 4, 3])

In [37]:
np.random.permutation(x) #`np.random.permutation(x)` returns a new array with the elements of `x` randomly shuffled.

array([2, 3, 4, 1])