In [1]:
import numpy as np

In [7]:
#np.arange(Star,end,steps)
a=np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
e=np.arange(1,20,2) #odd
print(e)

[ 1  3  5  7  9 11 13 15 17 19]


In [13]:
np.linspace(1,5,4) #1 theke 5 4 difference

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [33]:
a=np.array([1,2])
print(a)

[1 2]


In [37]:
a=np.arange(1,13).reshape(2,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [41]:
a.ravel() #2 to one d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [43]:
a.flatten() #2d to one d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [45]:
a.transpose() # 2 /6 k 6/2

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [58]:
a1=np.arange(1,10).reshape(3,3)
a2=np.arange(1,10).reshape(3,3)
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
a1+a2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [62]:
np.subtract(a1,a2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [64]:
a1/a2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
np.divide(a1,a2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [68]:
a1*a2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [70]:
np.multiply(a1,a2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [72]:
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [74]:
print(a1@a2) #first row first colmun product then sum

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [76]:
a1.dot(a2)#matrix multiplication

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [80]:
a1.max()


9

In [82]:
a1.min()

1

In [84]:
a1.argmax() #maximum value index

8

In [86]:
a1.max(axis=0) #row wise ans dibe prottek column a highest value

array([7, 8, 9])

In [88]:
np.sum(a1) #a1 array sum


45

In [90]:
np.sum(a1,axis=0) #column wise sum


array([12, 15, 18])

In [92]:
np.sum(a1,axis=1) #roe wise sum

array([ 6, 15, 24])

In [94]:
np.mean(a1)#a1 er sum all then divide by total number

5.0

In [96]:
np.sqrt(a1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [98]:
np.std(a1) #standtard daviation

2.581988897471611

In [100]:
np.exp(a1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [104]:
np.log10(a1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])