In [1]:
#One_D_array_print
import numpy as np

In [8]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [10]:
b=np.array([1,2,3,4,5])
print(b)

[1 2 3 4 5]


In [12]:
type(b)

numpy.ndarray

In [14]:
#2darray
c=([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [24]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
a.size

5

In [28]:
print(c.size)

9


In [32]:
print(c.ndim) #koy dimention er

2


In [34]:
print(c.shape) #3 ta row 3 ta column

(3, 3)


In [36]:
mx_1s=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s) 

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [40]:
mx_1s=np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [46]:
print(mx_1s.dtype)

float64


In [48]:
mx_1s=np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [50]:
mx_0s=np.zeros((4,6))
print(mx_0s)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [52]:
mx_0s=np.zeros((4,6),dtype=bool)
print(mx_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [54]:
mx_0s=np.zeros((4,6),dtype=str)
print(mx_0s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [56]:
em_str=''
print(bool(em_str))

False


In [58]:
em_mx=np.empty((3,3))
print(em_mx)

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 1.405e-320]
 [0.000e+000 0.000e+000 0.000e+000]]
